### ISSUE TITLE
raise NotImplementedError

### ISSUE THREAD

**Issue by NiuMa-1234** [SkyworkAI/MoE-plus-plus#1]
Thank you for your wonderful job! But why the fwd in class Experts is 
    def forward(self, permuted_local_hidden_states, tokens_per_expert):
        raise NotImplementedError
It means this should be rewritten by ourselves

**Comment by jpthu17** [comment]
Each type of expert has a different forward. The Experts class is not called directly:

https://github.com/SkyworkAI/MoE-plus-plus/blob/7f439675dd015fa307a31443544f76fa3525ba92/MoE%2B%2B/moe_plus_plus_layer.py#L178

https://github.com/SkyworkAI/MoE-plus-plus/blob/7f439675dd015fa307a31443544f76fa3525ba92/MoE%2B%2B/moe_plus_plus_layer.py#L138-L148

**Comment by jpthu17** [comment]
We use ```self.experts.experts[expert](tokens)``` instead of ```self.experts(tokens)```, so NotImplementedError is not triggered.

**Comment by NiuMa-1234** [comment]
Understood. Many thanks.
